# Generated by Django 3.2.5 on 2021-08-06 17:23

import blog.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(blank=True, default='default-blog-post-sluf', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='thumbnail',
            field=models.ImageField(default='img/post-thumbnails/default.jpg', upload_to=blog.models.upload_location),
        ),
        migrations.AlterUniqueTogether(
            name='blogpost',
            unique_together={('title', 'author')},
        ),
        migrations.AlterUniqueTogether(
            name='userfollowing',
            unique_together={('follower', 'followed')},
        ),
    ]
