# Generated by Django 3.0.8 on 2021-08-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210827_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='introduction',
            field=models.TextField(max_length=1200),
        ),
    ]
